name: Publish NPM

on:
  push:
    branches:
    - production

jobs:
  publish:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install, Build, and Publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        npm ci
        npm run push
    - name: Notifying Success
      if: success()
      uses: rtCamp/action-slack-notify@v1.0.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: 'GitHub Actions'
        SLACK_CHANNEL: deployment
        SLACK_COLOR: 'good'
        SLACK_ICON: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
        SLACK_TITLE: 'Keiser.Air.eChip.WebUSB'
        SLACK_MESSAGE: 'Build Success'
    - name: Notifying Failure
      if: failure()
      uses: rtCamp/action-slack-notify@v1.0.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: 'GitHub Actions'
        SLACK_CHANNEL: deployment
        SLACK_COLOR: 'bad'
        SLACK_ICON: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
        SLACK_TITLE: 'Keiser.Air.eChip.WebUSB'
        SLACK_MESSAGE: 'Build Failure'
