name: Publish NPM

on:
  push:
    branches:
    - production

jobs:
  publish:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install, Build, and Publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        npm ci
        npm run push
    - name: Notifying
      uses: rtCamp/action-slack-notify@v1.0.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: 'GitHub Actions'
        SLACK_CHANNEL: deployment
        SLACK_COLOR: 'good'
        SLACK_ICON: ':aws-bot:'
        SLACK_TITLE: 'Publish Complete'
        SLACK_MESSAGE: 'Successfully published `echip-webusb`'
